### PR TITLE
Project Registry Description field 'Invalid Format' when return key is used

### LINKED ISSUE #166: Project Registry Description field 'Invalid Format' when return key is used
-Description field shows 'Invalid Format' message when return key is used. 
-'Invalid Format' message is not very specific, leaves the user wondering what they did wrong.

### PR DESCRIPTION
**Pull request by yhfreeman**
- providing a fix so the return key is accepted by profile form submission - description field
- updating the dashboard profile card so description can read return key and render new line
- updating snapshots
- renaming useValidator to getValidator to follow the naming conventions where useXXX is only for react state / hooks related stuff

Fixes #166

### CODE REVIEW

File: web/src/components/UI/newLineText.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+//
+
+import React from 'react';
+
+const NewlineText = (props: any) => {
```
Comment (jleach) [inline web/src/components/UI/newLineText.tsx:19]: Could add a typescript return type here `string | null`

**Review by jleach — APPROVED** [review]
